<?xml version="1.0" encoding="utf-8"?><Database Name="lifeyou_db" Class="KHAOSATDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=112.213.89.144;Initial Catalog=lifeyou_db;Persist Security Info=True;User ID=lifeyouuser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="khaoSat_HSSV_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Survey_Answer" Member="Survey_Answers" ThisKey="Id" OtherKey="QuestionId" Type="Survey_Answer" />
      <Association Name="Group_Question" Member="Group" ThisKey="GroupId" OtherKey="Id" Type="Group" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Survey_Answer" Member="Survey_Answers">
    <Type Name="Survey_Answer">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChooseLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Survey_Answer" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Tester_Survey_Answer" Member="Tester" ThisKey="TesterId" OtherKey="Id" Type="Tester" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Subjects" Member="tbl_Subjects">
    <Type Name="tbl_Subject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Subject_PointAverage" Member="PointAverages" ThisKey="Id" OtherKey="SubjectId" Type="PointAverage" />
    </Type>
  </Table>
  <Table Name="dbo.PointAverage" Member="PointAverages">
    <Type Name="PointAverage">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Eleven" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Twelve" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Block" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_Subject_PointAverage" Member="tbl_Subject" ThisKey="SubjectId" OtherKey="Id" Type="tbl_Subject" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Tester_PointAverage" Member="Tester" ThisKey="TesterId" OtherKey="Id" Type="Tester" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KhoiThi" Member="KhoiThis">
    <Type Name="KhoiThi">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Khoi" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Mon1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mon2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mon3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Provinces">
    <Type Name="Province">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ProvinceName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TruongTHPT" Member="TruongTHPTs">
    <Type Name="TruongTHPT">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenTruong" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_Question" Member="Questions" ThisKey="Id" OtherKey="GroupId" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.NhomNganh" Member="NhomNganhs">
    <Type Name="NhomNganh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.College" Member="Colleges">
    <Type Name="College">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTruong" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaTruong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LoaiTruong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CapBac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HienThi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="WebSite" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nganh" Member="Nganhs">
    <Type Name="Nganh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ma" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tester" Member="Testers">
    <Type Name="Tester">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Favorite" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WhereBirth" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="HightSchool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Scores" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SchoolTest" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="A" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="B" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="D" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Orther" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SchoolLearning" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsMatch" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Reason1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ResultR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNganh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Tester_Survey_Answer" Member="Survey_Answers" ThisKey="Id" OtherKey="TesterId" Type="Survey_Answer" />
      <Association Name="Tester_PointAverage" Member="PointAverages" ThisKey="Id" OtherKey="TesterId" Type="PointAverage" />
    </Type>
  </Table>
  <Table Name="dbo.DHCD_Nganh" Member="DHCD_Nganhs">
    <Type Name="DHCD_Nganh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNganh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaTruong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NamTuyenSinh" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KhoiThi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TuyenSinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNhom1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaNganh1" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="MaNhom2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaNganh2" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="KhaNang" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Passwords" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThichHocNganh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoiHocTHPT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TruongTHPT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ResultA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups_Nganh" Member="Groups_Nganhs">
    <Type Name="Groups_Nganh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NhomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Manganh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhaoSat_SinhVien" Member="KhaoSat_SinhViens">
    <Type Name="KhaoSat_SinhVien">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChooseLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SinhVienId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Summary_ResultGroup" Method="Summary_ResultGroup">
    <Parameter Name="SinhVienId" Parameter="sinhVienId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SoLan" Parameter="soLan" Type="System.Int32" DbType="Int" />
    <ElementType Name="Summary_ResultGroupResult">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetList_Answer_By_SinhVien" Method="GetList_Answer_By_SinhVien">
    <Parameter Name="SinhVienId" Parameter="sinhVienId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetList_Answer_By_SinhVienResult">
      <Column Name="SinhVienId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Q1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q13" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q14" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q15" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q16" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q18" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q19" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q20" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q21" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q22" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q23" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q24" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q25" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q26" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q27" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q28" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q29" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q30" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q33" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q34" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q35" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q36" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q37" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q38" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q39" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q41" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q42" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q43" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q44" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q45" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q46" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q47" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q48" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q49" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q50" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q51" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q52" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q53" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q54" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetList_Answer" Method="GetList_Answer">
    <ElementType Name="GetList_AnswerResult">
      <Column Name="TesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q13" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q14" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q15" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q16" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q18" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q19" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q20" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q21" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q22" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q23" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q24" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q25" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q26" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q27" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q28" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q29" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q30" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q33" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q34" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q35" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q36" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q37" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q38" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q39" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q41" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q42" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q43" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q44" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q45" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q46" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q47" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q48" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q49" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q50" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q51" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q52" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q53" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q54" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNganh" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>