//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDefaultValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDefaultValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDefaultValue", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm Son Việt , thiết kế quảng cáo,Thiết kế bao bì,Thiết kế Brochure, Thiết kế Catalogue, Thiết kế Name card, thiết kế website, Thiết kế nhãn mác,Thiết kế Poster, Thiết kế tiêu đề thư,  Thiết kế túi xách, Thiết kế &amp; Thi Công hộp đèn-mặt dựng ALU, In lịch Tết, trang trí Noel, đèn LED, thiet ke quang cao, thiet ke bao bi, thiet ke website, thiet ke nhan mac, thiet ke poster, thiet ke tieu de thu, thiet ke tui xach, thiet ke va thi cong hop den - mat dung ALU, in lich, trang tri Noel, den LED.
        /// </summary>
        internal static string METADESCRIPTION {
            get {
                return ResourceManager.GetString("METADESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm Son Việt , thiết kế quảng cáo,Thiết kế bao bì,Thiết kế Brochure, Thiết kế Catalogue, Thiết kế Name card, thiết kế website, Thiết kế nhãn mác,Thiết kế Poster, Thiết kế tiêu đề thư,  Thiết kế túi xách, Thiết kế &amp; Thi Công hộp đèn-mặt dựng ALU, In lịch Tết, trang trí Noel, thiet ke quang cao, thiet ke bao bi, thiet ke website, thiet ke nhan mac, thiet ke poster, thiet ke tieu de thu, thiet ke tui xach, thiet ke va thi cong hop den - mat dung ALU, in lich, trang tri noel..
        /// </summary>
        internal static string METAKEYWORD {
            get {
                return ResourceManager.GetString("METAKEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm Son Việt - thiết kế - in ấn - thi công - design - POSM - printing - Decor - trang trí - Noel - lịch - quảng cáo - bảng hiệu - Mica - ALU - LED - Logo - Poster  - Tờ rơi - Showroom - Hội chợ - triển lãm - sự kiện - Hộp đèn.
        /// </summary>
        internal static string METATITLE {
            get {
                return ResourceManager.GetString("METATITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Chọn Danh Mục ---.
        /// </summary>
        internal static string SELECT_CATE {
            get {
                return ResourceManager.GetString("SELECT_CATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Chọn Danh Mục Cha ---.
        /// </summary>
        internal static string SELECT_CATE_PARENT {
            get {
                return ResourceManager.GetString("SELECT_CATE_PARENT", resourceCulture);
            }
        }
    }
}
