//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ..
        /// </summary>
        internal static string ERR_ADDRESS {
            get {
                return ResourceManager.GetString("ERR_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Tên Danh Mục..
        /// </summary>
        internal static string ERR_CATENAME {
            get {
                return ResourceManager.GetString("ERR_CATENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mã xác nhận..
        /// </summary>
        internal static string ERR_CODE {
            get {
                return ResourceManager.GetString("ERR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng. Vui lòng nhập lại..
        /// </summary>
        internal static string ERR_CODE_INVALID {
            get {
                return ResourceManager.GetString("ERR_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập công ty..
        /// </summary>
        internal static string ERR_COMPANY {
            get {
                return ResourceManager.GetString("ERR_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên nôi dung..
        /// </summary>
        internal static string ERR_CONTENT_NAME {
            get {
                return ResourceManager.GetString("ERR_CONTENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tiêu đề..
        /// </summary>
        internal static string ERR_CONTENT_TITILE {
            get {
                return ResourceManager.GetString("ERR_CONTENT_TITILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ Tự Phải Là Số..
        /// </summary>
        internal static string ERR_DISPLAYORDER {
            get {
                return ResourceManager.GetString("ERR_DISPLAYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Email..
        /// </summary>
        internal static string ERR_EMAIL {
            get {
                return ResourceManager.GetString("ERR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không đúng..
        /// </summary>
        internal static string ERR_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("ERR_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ tên..
        /// </summary>
        internal static string ERR_FULLNAME {
            get {
                return ResourceManager.GetString("ERR_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Links..
        /// </summary>
        internal static string ERR_LINKS {
            get {
                return ResourceManager.GetString("ERR_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên liên kết..
        /// </summary>
        internal static string ERR_LINK_NAME {
            get {
                return ResourceManager.GetString("ERR_LINK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập điện thoại..
        /// </summary>
        internal static string ERR_PHONE {
            get {
                return ResourceManager.GetString("ERR_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung ngắn..
        /// </summary>
        internal static string ERR_SHORT_CONTENT {
            get {
                return ResourceManager.GetString("ERR_SHORT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ của bạn đã được gửi thành công. Chúng tôi sẽ liên lạc với bạn trong thời gian sớm nhất. Xin chân thành cảm ơn..
        /// </summary>
        internal static string MESS_SEND_MAIL {
            get {
                return ResourceManager.GetString("MESS_SEND_MAIL", resourceCulture);
            }
        }
    }
}
